config/routes.rb
Rails.application.routes.draw do
  
  resources :enrollments
  devise_for :users, controllers: { registrations: "registrations", omniauth_callbacks: 'users/omniauth_callbacks'}
  resources :lessons
  resources :courses do
    resources :lessons
    resources :enrollments, only: [:new, :create]
  end
  resources :users, only: [:index, :edit, :show, :update]
  get 'home/index'
  get 'home/activity'
  root 'home#index'
  
  # root "static_pages#landing_page"
  # get 'privacy_policy', to: "static_pages#privacy_policy"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :course
  belongs_to :user
  
  #there can not be an enrollment that doesnt belong to a course and a user
  validates :user, :course, presence: true 
  
  validates_uniqueness_of :user_id, scope: :course_id  #user cant be subscribed to the same course twice
  validates_uniqueness_of :course_id, scope: :user_id  #user cant be subscribed to the same course twice
  
  validate :cant_subscribe_to_own_course  #user can't create a subscription if course.user == current_user.id


  def to_s
    user.to_s + " " + course.to_s
  end
  
  protected
  def cant_subscribe_to_own_course
    if self.new_record?
      if self.user_id.present?
        if self.user_id == course.user_id
          errors.add(:base, "You can not subscribe to your own course")
        end
      end
    end
  end
  
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  before_action :set_enrollment, only: %i[ show edit update destroy ]
  before_action :set_course, only: [:new, :create]

  # GET /enrollments or /enrollments.json
  def index
    @enrollments = Enrollment.all
    authorize @enrollments
  end

  # GET /enrollments/1 or /enrollments/1.json
  def show
  end

  # GET /enrollments/new
  def new
    @enrollment = Enrollment.new
  end

  # GET /enrollments/1/edit
  def edit
    authorize @enrollment
  end

  # POST /enrollments or /enrollments.json
  def create
    if @course.price > 0
      flash[:alert] = "You can not access paid courses yet."
      redirect_to new_course_enrollment_path(@course)
    else
      @enrollment = current_user.buy_course(@course)
      redirect_to course_path(@course), notice: "You are enrolled!"
    end
  end

  # PATCH/PUT /enrollments/1 or /enrollments/1.json
  def update
    authorize @enrollment
    respond_to do |format|
      if @enrollment.update(enrollment_params)
        format.html { redirect_to enrollment_url(@enrollment), notice: "Enrollment was successfully updated." }
        format.json { render :show, status: :ok, location: @enrollment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enrollments/1 or /enrollments/1.json
  def destroy
    authorize @enrollment
    @enrollment.destroy

    respond_to do |format|
      format.html { redirect_to enrollments_url, notice: "Enrollment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_course
      @course = Course.find(params[:course_id])
    end
    
    # Use callbacks to share common setup or constraints between actions.
    def set_enrollment
      @enrollment = Enrollment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def enrollment_params
      params.require(:enrollment).permit(:course_id, :user_id, :rating, :review)
    end
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/views/enrollments/_enrollment.html.haml
%p#notice= notice

%p
  %b Course:
  = @enrollment.course
%p
  %b User:
  = @enrollment.user
%p
  %b Rating:
  = @enrollment.rating
%p
  %b Review:
  = @enrollment.review
%p
  %b Price:
  = @enrollment.price

<br>
= link_to 'Edit', edit_enrollment_path(@enrollment), class: 'btn btn-warning'
= link_to 'Back', enrollments_path, class: 'btn btn-secondary'

app/views/enrollments/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@enrollment) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.association :course
    = f.association :user
    = f.input :rating
    = f.input :review
    <br>
    .form-actions
    // = f.button :submit, class: 'btn btn-success'
    <br>

app/views/enrollments/edit.html.haml
%h1
  .text-center
    Edit enrollment
<br>
= render 'form'


<br>
= link_to 'Show', @enrollment, class: 'btn btn-primary'
= link_to 'Back', enrollments_path, class: 'btn btn-secondary'

app/views/enrollments/index.html.haml
%h1
  .text-center
    Enrollments
<br>
%table.table
  %thead.thead.t-custom
    %tr
      %th ID
      %th 
        .fa.fa-clock
        Date enrolled
      %th 
        .fa.fa-user
        User
      %th 
        .fa.fa-graduation-cap
        Course
      %th
        .fa.fa-dollar-sign
        Price
      %th
        .text-warning.fa.fa-clock
        Reviewed on
      %th
        .text-warning.fa.fa-star
        Rating
      %th
        .text-warning.fa.fa-comment
        Review
      %th
      %th
      %th

  %tbody
    - @enrollments.each do |enrollment|
      %tr
        %td= enrollment.id
        %td= enrollment.created_at.strftime("%d.%m.%Y. - %Hh:%M:%S")
        %td= link_to enrollment.user, user_path(enrollment.user)
        %td= link_to enrollment.course, course_path(enrollment.course)
        %td= number_to_currency(enrollment.price)
        %td
          -if enrollment.rating.present?
            = enrollment.updated_at.strftime("%d.%m.%Y. - %Hh:%M:%S")
        %td= enrollment.rating
        %td= enrollment.review
        %td= link_to 'See Review', enrollment, class: 'btn btn-sm btn-primary'
        %td
          -if policy(enrollment).edit?
            = link_to 'Add Review', edit_enrollment_path(enrollment), class: 'btn btn-sm btn-warning'
        %td= link_to 'Delete Enrollment', enrollment, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger'

%br

= link_to 'New Enrollment', new_enrollment_path, class: 'btn btn-success'

app/views/enrollments/new.html.haml
.card
  .card-header
    %h3
      .fa.fa-graduation-cap
      = link_to @course.title, course_path(@course)
      %hr
      .fa.fa-lock-open
      /New enrollment
      Buy course
  .card-body
    = render 'form'
    = form_tag course_enrollments_path(@course) do
      = submit_tag "Pay #{@course.price}", class: 'btn btn-lg btn-success'
  .card-footer
    = link_to 'Back', course_path(@course)

app/views/enrollments/show.html.haml
= render 'enrollments/enrollment', enrollment: @enrollment