config/routes.rb
Rails.application.routes.draw do
  
  resources :enrollments
  devise_for :users, controllers: { registrations: "registrations", omniauth_callbacks: 'users/omniauth_callbacks'}
  resources :lessons
  resources :courses do
    resources :lessons
    resources :enrollments, only: [:new, :create]
  end
  resources :users, only: [:index, :edit, :show, :update]
  get 'home/index'
  get 'home/activity'
  root 'home#index'
  
  # root "static_pages#landing_page"
  # get 'privacy_policy', to: "static_pages#privacy_policy"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :course
  validates :title, :content, :course, presence: true
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_lesson, only: %i[ show edit update destroy ]

  # GET /lessons or /lessons.json
  def index
    @lessons = Lesson.all
  end

  # GET /lessons/1 or /lessons/1.json
  def show
  end

  # GET /lessons/new
  def new
    @lesson = Lesson.new
  end

  # GET /lessons/1/edit
  def edit
  end

  # POST /lessons or /lessons.json
  def create
    @lesson = Lesson.new(lesson_params)

    respond_to do |format|
      if @lesson.save
        format.html { redirect_to lesson_url(@lesson), notice: "Lesson was successfully created." }
        format.json { render :show, status: :created, location: @lesson }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lessons/1 or /lessons/1.json
  def update
    respond_to do |format|
      if @lesson.update(lesson_params)
        format.html { redirect_to lesson_url(@lesson), notice: "Lesson was successfully updated." }
        format.json { render :show, status: :ok, location: @lesson }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lessons/1 or /lessons/1.json
  def destroy
    @lesson.destroy

    respond_to do |format|
      format.html { redirect_to lessons_url, notice: "Lesson was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lesson
      @lesson = Lesson.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def lesson_params
      params.require(:lesson).permit(:title, :content, :course_id)
    end
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/lessons/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@lesson) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :title
    = f.input :content
    // input course_id and the value is going to be either the course_is that is already assigned
    // to the lesson or the course_id that is in params
    = f.input :course_id, input_html: {value: @lesson.course_id || params[:course_id]}, as: :hidden

  <br>
  .form-actions
    = f.button :submit, class: 'btn btn-success'
  <br>

app/views/lessons/_lesson.html.haml
.card
  .card-header
    = link_to lesson.title, lesson
  .card-body
    = lesson.content
    = lesson.course
  .card-footer.bg-white
    = link_to 'Edit', edit_lesson_path(lesson), class: 'btn btn-sm btn-warning'
    = link_to 'Destroy', lesson, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger'

app/views/lessons/edit.html.haml
%h1
  .text-center
    Edit lesson

= render 'form'

.container
= link_to 'Show', @lesson, class: 'btn btn-sm btn-primary'
= link_to 'Back', lessons_path, class: 'btn btn-sm btn-secondary'

app/views/lessons/index.html.haml
%h1
  .text-center
    All lessons
<br>
%table.table
  %thead.thead.t-custom
    %tr
      %th Title
      %th Content
      %th Course
      %th
      %th
      %th

  %tbody
    - @lessons.each do |lesson|
      %tr
        %td= lesson.title
        %td= lesson.content
        %td= lesson.course
        %td= link_to 'Show', lesson, class: 'btn btn-sm btn-primary'
        %td= link_to 'Edit', edit_lesson_path(lesson), class: 'btn btn-sm btn-warning'
        %td= link_to 'Destroy', lesson, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger'

%br

= link_to 'New Lesson', new_lesson_path, class: 'btn btn-success'

app/views/lessons/new.html.haml
%h1
  .text-center
    New lesson
    
= render 'form'

= link_to 'Back', lessons_path, class: 'btn btn-secondary'

app/views/lessons/show.html.haml
// %p#notice= notice
//= render 'lessons/lesson', lesson: @lesson

<br>
.jumbotron
.container-fluid
  %h1.display-8=@lesson.title
  %p.lead=@lesson.content
  <br>
  .container-fluid
  = link_to 'Edit', edit_lesson_path(@lesson), class: 'btn btn-warning'
  = link_to 'Back to course', course_path(@lesson.course), class: 'btn btn-secondary'
  %hr.my-4/

<br>