config/routes.rb
Rails.application.routes.draw do
  
  resources :enrollments
  devise_for :users, controllers: { registrations: "registrations", omniauth_callbacks: 'users/omniauth_callbacks'}
  resources :lessons
  resources :courses do
    resources :lessons
    resources :enrollments, only: [:new, :create]
  end
  resources :users, only: [:index, :edit, :show, :update]
  get 'home/index'
  get 'home/activity'
  root 'home#index'
  
  # root "static_pages#landing_page"
  # get 'privacy_policy', to: "static_pages#privacy_policy"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.haml
%hr
%footer
  .container
    .row
      .col-md-4
        Copyright
        © 
        = Time.now.year
        R-Syllabus 
        .row
        .fa.fa-envelope
        = mail_to 'ljovanovic5919rn@raf.rs'
        .row
      .col-md-4
        Privacy policy
        .row
        Terms and conditions
      .col-md-4
        About us
        .row
        = link_to 'Teach on R-Syllabus', new_course_path
%br 

app/views/layouts/_google_analytics.html.erb
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-LY4V3ZXFYV"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-LY4V3ZXFYV');
</script>

app/views/layouts/_header.html.haml
%nav.navbar.navbar-expand-lg.navbar-custom
  %a.navbar-brand{:href => "#"}  R-Syllabus
  %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-bs-target" => "#navbarSupportedContent", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  #navbarSupportedContent.collapse.navbar-collapse
    - if current_user
      %ul.navbar-nav.me-auto
        %li.nav-item{class: "#{'active fw-bold' if current_page?(root_path)}"}
          = link_to root_path, class: 'nav-link' do
            .fa.fa-home
            Home
        %li.nav-item{class: "#{'active fw-bold' if current_page?(courses_path)}"}
          = link_to courses_path, class: 'nav-link' do
            .fa.fa-book
            Courses
        %li.nav-item{class: "#{'active font-weight-bold' if current_page?(new_course_path)}"}
          = link_to new_course_path, class: 'nav-link' do
            .fa.fa-plus
            New Course
        %li.nav-item{class: "#{'active font-weight-bold' if current_page?(users_path)}"}
          = link_to users_path, class: 'nav-link' do
            .fa.fa-users
            Users
        %li.nav-item{class: "#{'active font-weight-bold' if current_page?(lessons_path)}"}
          = link_to lessons_path, class: 'nav-link' do
            .fa.fa-graduation-cap
            Lessons
        %li.nav-item{class: "#{'active font-weight-bold' if current_page?(enrollments_path)}"}
          = link_to enrollments_path, class: 'nav-link' do
            .fa.fa-building-columns
            Enrollments
      .form-inline.my-2.my-lg-0
        = form_tag(courses_path, method: :get) do
          .input-group
            = text_field_tag :title, params[:title], autocomplete: 'off', placeholder: "Search", class: 'form-control-sm'
            %span.input-group-append
              %button.btn.btn-primary.btn-sm{:type => "submit"}
                %span.fa.fa-search{"aria-hidden" => "true"}
      %ul.navbar-nav.mr-right
        %li.nav-item{class: "#{'active fwt-bold' if current_page?(home_activity_path)}"}
          = link_to home_activity_path, class: 'nav-link' do
            .fa.fa-bell
            Activity
        %li.nav-item.dropdown
          %a#navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-bs-toggle" => "dropdown", :href => "#", :role => "button"}
            %b= current_user.email
          .dropdown-menu.dropdown-menu-right{"aria-labelledby" => "navbarDropdown"}
            = link_to edit_user_registration_path, class: "dropdown-item" do
              .fa.fa-cog
              %b Account settings
            = link_to destroy_user_session_path, method: :delete, class: "dropdown-item" do
              .fa.fa-sign-out-alt
              %b Sign out
    - else
      %ul.navbar-nav
        %li.nav-item= link_to 'Sign Up', new_user_registration_path, class: 'nav-link'
        %li.nav-item= link_to 'Log In', new_user_session_path, class: 'nav-link'


- if current_user
  = current_user.email
  = link_to 'Account settings', edit_user_registration_path
  = link_to 'Sign out', destroy_user_session_path, method: :delete
- else
  = link_to 'Sign Up', new_user_registration_path
  = link_to 'Log In', new_user_session_path 
  = link_to "Sign in with Google", user_google_oauth2_omniauth_authorize_path 
  = link_to "Sign in with Google", user_google_oauth2_omniauth_authorize_path, method: :post 

app/views/layouts/_messages.html.haml
- flash.each do |key, value|
  %div{:class => "card-body d-flex list-group-item-#{key.to_s == 'notice' ? 'success' : 'danger'}", :role => "message"}
    %a{"data-bs-dismiss" => "message", :href => "#"}
      %i.fa.fa-window-close
    = value
    
  <br>
  

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    = favicon_link_tag 'logo.png'
    %title RSyllabus
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = render 'layouts/google_analytics'
  %body
  .container-fluid  
    = render 'layouts/header'
    <br>
    = render 'layouts/messages'
    <br>
    = yield
    <br
    <br>
    <br>
    <br>
    <br>
    <br>
    .container-center
      = render 'layouts/footer'